package day14_Exception;

import java.util.Scanner;

public class Ex01 {
	public static void main(String[] args) {
		/*
		 * 예외처리
		 * -프로그램 의도(개발자의도)와 다르게 동작하는 것들
		 * 예외 종류
		 * - 강제예외 : throw
		 * - 예외전가 : throws
		 * - 예외처리 : try, catch
		 */
		Scanner sc = new Scanner(System.in);
		int x,y, result;
		System.out.println("수 입력");
		x = sc.nextInt();
		y = sc.nextInt();
		try {	
			result = x/y;
			System.out.println("x/y = " + result);
		}catch(ArithmeticException e) {
			e.printStackTrace();
		}
		System.out.println("다음 문장들 실행~");
	}
}
